Improvements
pbadenski/bull-prom pull request #3
Opened 2020-05-19 23:09 UTC by robbiet480

- Duration summary
- Multi-queue support

Thanks @mjgp2!

2020-05-20 08:01 UTC, pbadenski commented
I'm a bit out of touch with changes in bull, could you explain a bit about this pull request?

2020-05-20 14:56 UTC, mjgp2 commented
Not bull specific, just adds the ability to bind to multiple queues, and a duration metric.

2020-05-20 16:49 UTC, pbadenski requested changes

2020-05-20 16:49 UTC, pbadenski commented on lib/index.js
> +    const durationMetricName = 'jobs_duration';
Could you change metric name to include time unit (milliseconds?). See: https://prometheus.io/docs/practices/naming/#metric-names

2020-05-20 16:49 UTC, pbadenski commented on package.json
> +  "version": "1.2.0",
Can you remove this change? I'm going to version and release separately.

2020-05-29 02:05 UTC, robbiet480 commented
Closing in favor of #5

2020-05-29 02:05 UTC, closed without merging